#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

/usr/sbin/httpd -h /www/

ip link set eth0 up
ip addr add 192.168.0.100/24 dev eth0

mount /dev/mmcblk0p6 /www/upload/files

mount -t tmpfs tmpfs /var/log
